name: Build, Test & Deploy .NET App via FTPS

on:
  push:
    branches: [ "main" ]

jobs:
  # ðŸ§± 1. Build
  build:
    runs-on: self-hosted
    name: Build .NET Project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        env:
          DOTNET_INSTALL_DIR: C:\actions-runner\dotnet

      - name: Restore dependencies
        run: dotnet restore ./src/HelloWorldMvc/HelloWorldMvc.csproj

      - name: Build project
        run: dotnet build ./src/HelloWorldMvc/HelloWorldMvc.csproj -c Release --no-restore

      - name: Publish project
        run: dotnet publish ./src/HelloWorldMvc/HelloWorldMvc.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: ./publish/

  # ðŸ§ª 2. Test
  test:
    runs-on: self-hosted
    needs: build
    name: Run Integration Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        env:
          DOTNET_INSTALL_DIR: C:\actions-runner\dotnet

      - name: Restore test dependencies
        run: dotnet restore ./test/IntegrationTest/IntegrationTest.csproj

      - name: Build test project
        run: dotnet build ./test/IntegrationTest/IntegrationTest.csproj -c Release --no-restore

      - name: Run integration tests
        run: dotnet test ./test/IntegrationTest/IntegrationTest.csproj -c Release --no-build --verbosity normal

  deploy:
    runs-on: self-hosted
    needs: test
    name: Deploy to Azure Web App
    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package
          path: ./publish
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: photomvc-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

