name: Build & Deploy Combined .NET App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    name: Build .NET Project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        env:
          DOTNET_INSTALL_DIR: C:\actions-runner\dotnet

      - name: Restore dependencies
        run: dotnet restore ./src/HelloWroldMvc/HelloWroldMvc.csproj

      - name: Build project
        run: dotnet build ./src/HelloWroldMvc/HelloWroldMvc.csproj -c Release --no-restore

      - name: Publish project
        run: dotnet publish ./src/HelloWroldMvc/HelloWroldMvc.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: ./publish/

  deploy:
    runs-on: self-hosted
    needs: build
    name: Deploy to Azure Web App

    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'photomvc-app'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
